version: '3'

services:
  nginx:
    image: nginx:1.25.4-alpine
    volumes:
      - .:/var/www
      - ./docker/nginx/templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      - php-fpm
    restart: on-failure
    networks:
      - blog_net

  php-fpm:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www
    depends_on:
      - blog_db
    restart: on-failure
    command: > 
      sh -c "echo yes | php /var/www/bin/doctrine.php migrate && php-fpm || nginx"
    networks:
      - blog_net


  blog_db:
    image: postgres:17
    restart: on-failure
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
        - blog_net

volumes:
  postgres-db:

networks:
  blog_net:
    driver: bridge